version: '3'
services:
  vendor-portal:
    image: dmitrysavin/selenium
    environment:
    - BROWSER=chrome
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=vendor-portal.xml
    volumes:
      - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservations:
    image: dmitrysavin/selenium
    environment:
    - BROWSER=firefox
    - HUB_HOST=hub
    - THREAD_COUNT=3
    - TEST_SUITE=flight-reservations.xml
    volumes:
      - ./output/flight-reservations:/home/selenium-docker/test-output
